[build]
  command   = "pnpm run build"      # Enhanced Giggles Go Dashboard build
  publish   = ".netlify/output"      # where the plugin will emit your static assets
  functions = ".netlify/functions"   # where the plugin will emit your SSR/Edge functions

[[plugins]]
  package = "@netlify/plugin-nextjs"
